### ISSUE TITLE
Error dist undefined when launching stack, docker, vm, docker-compose, all same 

### ISSUE THREAD

**Issue by tsunamireversal** [mozilla/send#1152]
The web site on :1443 displays only this... why ?

```
Error: Cannot find module '../dist/undefined'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.serverTranslator [as getTranslator] (/root/send/common/locales.js:21:10)
    at module.exports (/root/send/server/state.js:9:24)
    at index (/root/send/server/routes/pages.js:13:47)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/send/node_modules/express/lib/router/route.js:137:13)
    at module.exports (/root/send/server/middleware/language.js:43:3)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/send/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/send/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at /root/send/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/root/send/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/send/node_modules/express/lib/router/index.js:317:13)
    at /root/send/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at /root/send/server/routes/index.js:52:5
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/send/node_modules/express/lib/router/index.js:317:13)
    at /root/send/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at hsts (/root/send/node_modules/hsts/index.js:42:5)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/send/node_modules/express/lib/router/index.js:317:13)
    at /root/send/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at internalNext (/root/send/node_modules/helmet/index.js:47:33)
    at xXssProtection (/root/send/node_modules/x-xss-protection/index.js:26:7)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at nosniff (/root/send/node_modules/dont-sniff-mimetype/index.js:4:5)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at ienoopen (/root/send/node_modules/ienoopen/index.js:4:5)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at hsts (/root/send/node_modules/hsts/index.js:42:5)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at hidePoweredBy (/root/send/node_modules/hide-powered-by/index.js:12:7)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at frameguard (/root/send/node_modules/frameguard/index.js:38:5)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at dnsPrefetchControl (/root/send/node_modules/dns-prefetch-control/index.js:10:7)
    at internalNext (/root/send/node_modules/helmet/index.js:51:7)
    at helmet (/root/send/node_modules/helmet/index.js:54:5)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/send/node_modules/express/lib/router/index.js:317:13)
    at /root/send/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/root/send/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/send/node_modules/express/lib/router/index.js:317:13)
    at /root/send/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at query (/root/send/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/root/send/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/send/node_modules/express/lib/router/index.js:317:13)
    at /root/send/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/send/node_modules/express/lib/router/index.js:335:12)
    at next (/root/send/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/send/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/root/send/node_modules/express/lib/application.js:174:10)
    at Server.app (/root/send/node_modules/express/lib/express.js:39:9)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```
I'm happy to help troubleshoot. Tried Docker 18.09, docker-compose 1.23, and bare metal vm Ubuntu 18.04 LTS with dev and prod.

Had to manually install the following deps for stack to run

```
npm install express
npm install raven
npm install redis-mock
npm install convict
npm install connect-busboy
npm install helmet
npm install mozlog
npm install fluent-langneg
npm install cldr-core
npm install choo
npm install base64-js
```

**Comment by dannycoates** [comment]
After cloning the repo what commands did you run? Did you follow https://github.com/mozilla/send/blob/master/docs/build.md#production?
