### ISSUE TITLE
Docker container failing

### ISSUE THREAD

**Issue by dantuluri** [mozilla/send#1263]
I followed the instructions in [https://github.com/mozilla/send/blob/master/docs/docker.md](https://github.com/mozilla/send/blob/master/docs/docker.md)
by doing the following:

```
npm install
npm run build
```
Running `docker-compose up` or `npm start` work fine. 
Yet when running `docker run` after building the image, I'm getting the following errors:
```
FirefoxSend.CRITICAL: uncaughtException Error: Cannot find module 'redis-mock'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/app/server/storage/redis.js:10:17)
    at new DB (/app/server/storage/index.js:24:18)
    at Object.<anonymous> (/app/server/storage/index.js:82:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/server/routes/index.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/server/bin/prod.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
I've tried inserting `RUN npm install` and `RUN npm run build` within the Dockerfile, but I run into #867.

How should I go around this issue. By the way, I'm eventually trying to run this on Kubernetes and from this initial testing (docker run) it not going to work.

**Comment by dannycoates** [comment]
You need to set the `REDIS_HOST` environment variable, like the example in docker.md. The docker image doesn't contain `devDependencies`

**Comment by dantuluri** [comment]
Thanks for the help, I completely forgot about running docker with all the env variables.

When running the docker container, should there be any output? Will it run on localhost:1443?
