### ISSUE TITLE
Release v3.0.12 build fails

### ISSUE THREAD

**Issue by SaulMoonves** [mozilla/send#1357]
Not sure exactly how to run/build releases so I tried just running it (fails missing node_modules) npm install (broken site), npm install && npm run build (fails with below error.)
```
send@send:~/send$ npm run build

> firefox-send@3.0.12 build /home/send/send
> npm run clean && webpack


> firefox-send@3.0.12 clean /home/send/send
> rimraf dist

/home/send/send/node_modules/webpack-cli/bin/cli.js:74
                throw err;
                ^

Error: [git-rev-sync] no git repository found
    at _getGitDirectory (/home/send/send/node_modules/git-rev-sync/index.js:47:11)
    at _getGitDirectory (/home/send/send/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/home/send/send/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/home/send/send/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/home/send/send/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/home/send/send/node_modules/git-rev-sync/index.js:75:10)
    at branch (/home/send/send/node_modules/git-rev-sync/index.js:79:16)
    at long (/home/send/send/node_modules/git-rev-sync/index.js:92:11)
    at Object.short (/home/send/send/node_modules/git-rev-sync/index.js:118:10)
    at Object.<anonymous> (/home/send/send/build/version_plugin.js:1:102)
    at Module._compile (/home/send/send/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/send/send/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/send/send/webpack.config.js:5:23)
    at Module._compile (/home/send/send/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/send/send/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/send/send/node_modules/webpack-cli/bin/utils/convert-argv.js:115:13)
    at requireConfig (/home/send/send/node_modules/webpack-cli/bin/utils/convert-argv.js:117:6)
    at /home/send/send/node_modules/webpack-cli/bin/utils/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/send/send/node_modules/webpack-cli/bin/utils/convert-argv.js:122:15)
    at yargs.parse (/home/send/send/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/send/send/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/send/send/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/send/send/node_modules/webpack-cli/bin/cli.js:375:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firefox-send@3.0.12 build: `npm run clean && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the firefox-send@3.0.12 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/send/.npm/_logs/2019-06-26T15_26_38_539Z-debug.log
```

**Comment by oliver-dvorski** [comment]
Not sure why you'd need to run the build script with a release... But I was able to reproduce this by deleting my .git folder within the source code. This folder isn't packed with the releases. Meaning if you want to run the build script, you should clone the repo, run `npm install` and off you go :) the build script should work just fine after that

**Comment by SaulMoonves** [comment]
If I just unpack the release, modify the config file and start, I get a blank white page with some broken image references, so I assumed there was some extra step I was missing. Maybe that should have been the issue I filed.

**Comment by oliver-dvorski** [comment]
I think, with the releases, you're only supposed to run `npm run prod`. This will spin up the server at `localhost:1443`. The release already contains the assets that `npm run build` creates.

**Comment by clouserw** [comment]
Please review the community-contributed deployment instructions at https://github.com/mozilla/send/blob/master/docs/deployment.md
