### ISSUE TITLE
Error on npm run build due to webpack?

### ISSUE THREAD

**Issue by krosseyed** [mozilla/send#1389]
I keep running into an issue with trying to build send, and it seems that it is during the 'webpack' phase. Attached is the output of my debug.log file:

> $ cat /var/www/.npm/_logs/2019-09-05T14_03_17_888Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/usr/local/nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle firefox-send@3.0.16~prebuild: firefox-send@3.0.16
6 info lifecycle firefox-send@3.0.16~build: firefox-send@3.0.16
7 verbose lifecycle firefox-send@3.0.16~build: unsafe-perm in lifecycle true
8 verbose lifecycle firefox-send@3.0.16~build: PATH: /usr/local/nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/kylehagerty.com/send/node_modules/.bin:/usr/local/node/bin:/usr/local/nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle firefox-send@3.0.16~build: CWD: /var/www/kylehagerty.com/send
10 silly lifecycle firefox-send@3.0.16~build: Args: [ '-c', 'npm run clean && webpack' ]
11 silly lifecycle firefox-send@3.0.16~build: Returned: code: 2  signal: null
12 info lifecycle firefox-send@3.0.16~build: Failed to exec build script
13 verbose stack Error: firefox-send@3.0.16 build: `npm run clean && webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid firefox-send@3.0.16
15 verbose cwd /var/www/kylehagerty.com/send
16 verbose Linux 4.15.0-60-generic
17 verbose argv "/usr/local/nvm/versions/node/v10.16.3/bin/node" "/usr/local/nvm/versions/node/v10.16.3/bin/npm" "run" "build"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error firefox-send@3.0.16 build: `npm run clean && webpack`
22 error Exit status 2
23 error Failed at the firefox-send@3.0.16 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by krosseyed** [comment]
Looks like it was a permissions issue on my side in the directory node_modules directory. Set to the apache user and now it builds properly
