### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by asunyer90** [mozilla/send#792]
Hi!
I've installed nodejs.
Cloned git.
And then did npm install and npm start.
When I try to access to ip:8080 I get following error message:
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/home/user/git/send/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at Object.getLocaleWithMiddleware [as get] (/home/user/git/send/common/locales.js:37:41)
    at Object.instance.getTranslator (/home/user/git/send/common/locales.js:44:50)
    at module.exports (/home/user/git/send/server/state.js:9:24)
    at index (/home/user/git/send/server/routes/pages.js:13:47)
    at Layer.handle [as handle_request] (/home/user/git/send/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/git/send/node_modules/express/lib/router/route.js:137:13)
    at module.exports (/home/user/git/send/server/middleware/language.js:43:3)
    at Layer.handle [as handle_request] (/home/user/git/send/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/git/send/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/user/git/send/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/user/git/send/node_modules/express/lib/router/layer.js:95:5)
    at /home/user/git/send/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/user/git/send/node_modules/express/lib/router/index.js:335:12)
    at next (/home/user/git/send/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/user/git/send/node_modules/body-parser/lib/types/json.js:109:7)

**Comment by RCMainak** [comment]
You're trying to access the local webapp before webpack has done it work. To resolve this issue wait the following text in your terminal or command promt whatever you're using to run `npm start`

`webpack: Compiled successfully.` Try to access after you see this text.

**Comment by asunyer90** [comment]
I also get some warns while doing npm install (it might be for that thing..)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.5 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.

**Comment by RCMainak** [comment]
Maybe I'm not sure. Have you tried after webpack done it's compiling thingy.

**Comment by asunyer90** [comment]
Well. just tried to wait for the "npm start" finishes.
It says this:
 firefox-send@2.5.2 start /home/user/git/send
> npm run clean && cross-env NODE_ENV=development webpack-dev-server


> firefox-send@2.5.2 clean /home/user/git/send
> rimraf dist

Project is running at http://0.0.0.0:8080/
webpack output is served from /
user@user:~/git/send$

As you see, it finish the process withouth saying nothing else...

**Comment by dannycoates** [comment]
@asunyer90 try running these two commands and post the output:

```sh
npm run build
npm test
```

**Comment by asunyer90** [comment]
Hi!
I've alredy solved :)
It was a problem with the machine. Did not have enough resources "RAM/CPU" available to run the commands. 
Thank you!
